# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('capa', models.CharField(default='/static/assets/img/book-no-cover.jpg', max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('ISBN', models.CharField(max_length=20)),
                ('edicao', models.CharField(max_length=20)),
                ('editora', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('3', 'novo'), ('2', 'bom'), ('1', 'ruim')], default='2', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('avaliacaoDono', models.TextField()),
                ('avaliacaoSolicitante', models.TextField()),
                ('notaDono', models.IntegerField()),
                ('notaSolicitante', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Livro')),
                ('usuarioSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='home.Perfil'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='home.Perfil'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Transacao'),
        ),
        migrations.AddField(
            model_name='livro',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Perfil'),
        ),
    ]
