# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160606_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='nota_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='troca',
            name='nota_2',
            field=models.IntegerField(default=1),
        ),
    ]
