# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('conteudo', models.TextField()),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='home.Perfil')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='home.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('avaliacaoDono', models.TextField()),
                ('avaliacaoSolicitante', models.TextField()),
                ('notaDono', models.IntegerField()),
                ('notaSolicitante', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='ISBN',
            field=models.CharField(default='0001', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='data',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 26, 0, 4, 3, 872650, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='edicao',
            field=models.CharField(default='Primeira', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='estado',
            field=models.CharField(choices=[('3', 'novo'), ('2', 'bom'), ('1', 'ruim')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='transacao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Livro'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='usuarioSolicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Perfil'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Transacao'),
        ),
    ]
