# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_perfil_seguindo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troca',
            name='livro_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros_trocados', to='home.Livro'),
        ),
    ]
