# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160614_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to='home.Perfil'),
        ),
    ]
