# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160614_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='troca',
            name='concluida_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='troca',
            name='concluida_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='troca',
            name='perfil_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_1', to='home.Perfil'),
        ),
        migrations.AlterField(
            model_name='troca',
            name='perfil_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_2', to='home.Perfil'),
        ),
    ]
