# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160615_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='troca',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='troca',
            name='finalizada_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='troca',
            name='finalizada_2',
            field=models.BooleanField(default=False),
        ),
    ]
